In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [2]:

file_path = r"C:\Users\Lulu\Documents\Git\Projet_2\movies_step1.csv"
 # Lire le fichier CSV
df_movies1 = pd.read_csv(file_path, sep=',')

In [3]:
df_movies1.head()

,tconst,titleType,startYear,runtimeMinutes,averageRating,numVotes,Adventure,Family,Comedy,Biography,...,Musical,Western,History,Crime,Film-Noir,Horror,Romance,title,region,language
0,tt0053699,movie,1960.0,86,6.2,2858,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Constable,GB,en
1,tt0053715,movie,1960.0,147,6.4,3470,0,0,0,0,...,0,1,0,0,0,0,1,Cimarron,US,en
2,tt0053719,movie,1960.0,76,6.7,8650,0,0,0,0,...,0,0,0,0,0,1,0,The City of the Dead,GB,en
3,tt0053877,movie,1960.0,104,6.5,5885,0,0,1,0,...,0,0,0,0,0,0,1,"Ailleurs, l'herbe est plus verte",FR,fr
4,tt0054167,movie,1960.0,101,7.6,39971,0,0,0,0,...,0,0,0,0,0,1,0,Peeping Tom,GB,en

In [4]:
df_movies1['numVotes'].sort_values(ascending=False).value_counts()

numVotes
9          11
22          7
11          7
24          7
10          6
           ..
74285       1
73872       1
34          1
33          1
2923814     1
Name: count, Length: 1235, dtype: int64

In [5]:
df_movies1['numVotes'].mean()

np.float64(62899.210292249045)

In [7]:
df_movies1['numVotes'].median()

np.float64(1958.0)

In [8]:
df_movies1 = df_movies1[(df_movies1['numVotes'] >= 2324)]

In [9]:
df_movies1.head()

,tconst,titleType,startYear,runtimeMinutes,averageRating,numVotes,Adventure,Family,Comedy,Biography,...,Musical,Western,History,Crime,Film-Noir,Horror,Romance,title,region,language
0,tt0053699,movie,1960.0,86,6.2,2858,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Constable,GB,en
1,tt0053715,movie,1960.0,147,6.4,3470,0,0,0,0,...,0,1,0,0,0,0,1,Cimarron,US,en
2,tt0053719,movie,1960.0,76,6.7,8650,0,0,0,0,...,0,0,0,0,0,1,0,The City of the Dead,GB,en
3,tt0053877,movie,1960.0,104,6.5,5885,0,0,1,0,...,0,0,0,0,0,0,1,"Ailleurs, l'herbe est plus verte",FR,fr
4,tt0054167,movie,1960.0,101,7.6,39971,0,0,0,0,...,0,0,0,0,0,1,0,Peeping Tom,GB,en

In [10]:
df_unique = df_movies1.drop_duplicates(subset='tconst', keep='first')

In [11]:
df_unique.head(50)

,tconst,titleType,startYear,runtimeMinutes,averageRating,numVotes,Adventure,Family,Comedy,Biography,...,Musical,Western,History,Crime,Film-Noir,Horror,Romance,title,region,language
0,tt0053699,movie,1960.0,86,6.2,2858,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Constable,GB,en
1,tt0053715,movie,1960.0,147,6.4,3470,0,0,0,0,...,0,1,0,0,0,0,1,Cimarron,US,en
2,tt0053719,movie,1960.0,76,6.7,8650,0,0,0,0,...,0,0,0,0,0,1,0,The City of the Dead,GB,en
3,tt0053877,movie,1960.0,104,6.5,5885,0,0,1,0,...,0,0,0,0,0,0,1,"Ailleurs, l'herbe est plus verte",FR,fr
4,tt0054167,movie,1960.0,101,7.6,39971,0,0,0,0,...,0,0,0,0,0,1,0,Peeping Tom,GB,en
5,tt0054215,movie,1960.0,109,8.5,725728,0,0,0,0,...,0,0,0,0,0,1,0,Psycho,US,en
8,tt0054727,movie,1961.0,90,6.0,2527,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Regardless,GB,en
9,tt0055630,movie,1961.0,110,8.2,132696,0,0,0,0,...,0,0,0,0,0,0,0,The Bodyguard,US,en
10,tt0055831,movie,1962.0,89,6.1,3246,0,0,1,0,...,0,0,0,0,0,0,1,Carry on Cruising,GB,en
13,tt0056869,movie,1963.0,119,7.6,206777,0,0,0,0,...,0,0,0,0,0,1,0,The Birds,US,en
14,tt0057128,movie,1963.0,87,6.7,8639,0,0,0,0,...,0,0,0,0,0,1,0,The Haunted Palace,US,en
15,tt0057918,movie,1964.0,92,6.7,5052,1,0,1,0,...,0,0,0,0,0,0,1,Carry on Cleo,GB,en
16,tt0057919,movie,1964.0,91,5.9,2612,1,0,1,0,...,0,0,0,0,0,0,1,Carry on Jack,GB,en
17,tt0057920,movie,1964.0,87,6.2,3142,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Spying,GB,en
18,tt0058453,movie,1964.0,110,6.3,9554,0,0,1,0,...,0,0,0,0,0,0,1,Paris When It Sizzles,US,en
19,tt0058725,movie,1964.0,85,6.3,9344,0,0,1,0,...,1,0,0,0,0,0,0,Viva Las Vegas,US,en
20,tt0059014,movie,1965.0,93,6.2,3419,0,0,1,0,...,0,1,0,0,0,0,0,Carry on Cowboy,GB,en
22,tt0059245,movie,1965.0,260,6.6,12070,0,0,0,1,...,0,0,1,0,0,0,0,The Greatest Story Ever Told,US,en
23,tt0059250,movie,1965.0,165,6.4,4480,0,0,1,0,...,0,1,0,0,0,0,0,The Hallelujah Trail,US,en
24,tt0059719,movie,1965.0,45,7.8,10944,0,0,1,0,...,0,0,0,0,0,0,0,Simon du dÃ©sert,FR,fr
26,tt0060176,movie,1966.0,111,7.4,68328,0,0,0,0,...,0,0,0,0,0,0,0,Blow-Up,GB,en
27,tt0060214,movie,1966.0,97,6.7,5887,0,0,1,0,...,0,0,0,0,0,1,0,Carry on Screaming,GB,en
28,tt0060268,movie,1966.0,112,7.0,14073,0,0,1,0,...,0,0,0,0,0,0,0,Cul-de-sac,GB,en
29,tt0060330,movie,1967.0,90,6.5,3165,1,0,1,0,...,0,0,0,0,0,0,0,Carry on Don't Lose Your Head,GB,en
31,tt0060588,movie,1966.0,128,6.8,8366,1,0,0,0,...,0,0,0,0,0,0,0,Khartoum,GB,en
33,tt0061420,movie,1967.0,113,5.9,2808,0,0,0,0,...,0,0,0,0,0,0,0,The Born Losers,US,en
35,tt0061450,movie,1967.0,94,6.5,4194,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Doctor,GB,en
38,tt0061680,movie,1967.0,95,6.0,2707,1,0,1,0,...,0,0,0,0,0,0,1,Carry on Follow That Camel,GB,en
39,tt0061758,movie,1967.0,95,5.1,2733,0,0,0,0,...,0,0,0,1,0,0,0,Hells Angels on Wheels,US,en
40,tt0061811,movie,1967.0,110,7.9,84280,0,0,0,0,...,0,0,0,0,0,0,0,In the Heat of the Night,US,en
42,tt0062037,movie,1967.0,94,5.6,2378,0,0,0,0,...,0,0,0,0,0,1,0,Night of the Big Heat,GB,en
47,tt0062782,movie,1968.0,88,6.8,5525,1,0,1,0,...,0,0,0,0,0,0,0,Carry on Up the Khyber,GB,en
50,tt0063803,movie,1967.0,90,6.5,10228,0,0,0,0,...,0,0,0,0,0,0,0,Who's That Knocking at My Door,US,en
51,tt0064132,movie,1969.0,89,6.2,3057,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Again Doctor,GB,en
52,tt0064133,movie,1969.0,88,6.6,5911,0,0,1,0,...,0,0,0,0,0,0,0,Carry on Camping,GB,en
56,tt0064949,movie,1970.0,95,5.5,4506,0,0,0,0,...,0,0,0,1,0,1,0,Scream and Scream Again,GB,en
57,tt0065112,movie,1969.0,143,6.2,19741,0,0,0,0,...,0,0,0,0,0,0,0,Topaz,US,en
58,tt0065421,movie,1970.0,78,7.1,115949,1,0,1,0,...,0,0,0,0,0,0,0,The Aristocats,US,en
59,tt0065524,movie,1970.0,88,5.9,2680,0,0,1,0,...,0,0,0,0,0,0,1,Carry on Loving,GB,en
60,tt0065525,movie,1970.0,89,5.9,3205,1,0,1,0,...,0,0,0,0,0,0,0,Carry on Up the Jungle,GB,en
61,tt0065555,movie,1970.0,108,6.2,3539,0,0,0,0,...,0,0,0,1,0,0,0,Violent City,US,en
62,tt0065669,movie,1970.0,90,5.4,5262,0,0,0,0,...,0,0,0,0,0,1,0,The Dunwich Horror,US,en
64,tt0065904,movie,1970.0,71,2.4,2507,0,0,1,0,...,0,0,0,0,0,0,1,The Party at Kitty and Stud's,US,en
66,tt0066450,movie,1970.0,108,6.0,4423,0,0,0,0,...,0,0,0,1,0,0,0,They Call Me Mister Tibbs!,US,en
68,tt0066895,movie,1971.0,90,6.2,3588,0,0,1,0,...,0,0,0,0,0,0,0,Carry on at Your Convenience,GB,en
72,tt0067176,movie,1971.0,85,6.2,3055,0,0,0,0,...,0,0,0,0,0,1,0,Hands of the Ripper,GB,en
74,tt0067372,movie,1971.0,140,7.4,15109,0,0,0,0,...,0,0,1,0,0,0,0,Macbeth,GB,en
75,tt0067525,movie,1971.0,98,6.4,34364,0,0,0,0,...,0,0,0,0,0,0,0,The Omega Man,US,en
80,tt0067800,movie,1971.0,113,7.4,64983,0,0,0,0,...,0,0,0,1,0,0,0,Straw Dogs,GB,en
81,tt0067803,movie,1971.0,104,7.2,9246,0,0,0,0,...,0,0,0,0,0,0,1,Summer of '42,US,en

In [14]:
# SpÃ©cifiez le chemin du fichier CSV
file_path = 'C:/Users/Lulu/Documents/Git/Projet_2/movies_step2.csv'

# Enregistrer le DataFrame en fichier CSV
df_unique.to_csv(file_path, index=False)

print(f"Le fichier CSV a Ã©tÃ© enregistrÃ© Ã  : {file_path}")

Le fichier CSV a Ã©tÃ© enregistrÃ© Ã  : C:/Users/Lulu/Documents/Git/Projet_2/movies_step2.csv

### Table name basics

In [13]:
df_basics = pd.read_csv("https://datasets.imdbws.com/name.basics.tsv.gz", sep = "\t", usecols=['primaryName','primaryProfession','knownForTitles'], dtype={'primaryName':'str'})
df_basics.head(10)

,primaryName,primaryProfession,knownForTitles
0,Fred Astaire,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0053137,tt0027125"
1,Lauren Bacall,"actress,soundtrack,archive_footage","tt0037382,tt0075213,tt0117057,tt0038355"
2,Brigitte Bardot,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,John Belushi,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,Ingmar Bergman,"writer,director,actor","tt0050986,tt0083922,tt0050976,tt0069467"
5,Ingrid Bergman,"actress,producer,soundtrack","tt0034583,tt0036855,tt0038109,tt0038787"
6,Humphrey Bogart,"actor,producer,miscellaneous","tt0034583,tt0042593,tt0037382,tt0033870"
7,Marlon Brando,"actor,director,writer","tt0078788,tt0068646,tt0047296,tt0070849"
8,Richard Burton,"actor,producer,director","tt0061184,tt0087803,tt0059749,tt0057877"
9,James Cagney,"actor,director,producer","tt0029870,tt0031867,tt0042041,tt0055256"

In [13]:
df_basics.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13692582 entries, 0 to 13692581
Data columns (total 3 columns):
 #   Column             Dtype
---  ------             -----
 0   primaryName        object
 1   primaryProfession  object
 2   knownForTitles     object
dtypes: object(3)
memory usage: 2.7 GB

In [14]:
# Ã‰tape 1: SÃ©parer les chaÃ®nes en listes
df_basics['knownForTitles'] = df_basics['knownForTitles'].str.split(',')

# Ã‰tape 2: Ã‰clater les listes en lignes distinctes
df_exploded = df_basics.explode('knownForTitles')

In [15]:
df_exploded.head()

     primaryName                   primaryProfession knownForTitles
0   Fred Astaire        actor,miscellaneous,producer      tt0072308
0   Fred Astaire        actor,miscellaneous,producer      tt0050419
0   Fred Astaire        actor,miscellaneous,producer      tt0053137
0   Fred Astaire        actor,miscellaneous,producer      tt0027125
1  Lauren Bacall  actress,soundtrack,archive_footage      tt0037382

In [16]:
# SpÃ©cifiez le chemin du fichier CSV
file_path = 'C:/Users/Lulu/Documents/Git/Projet_2/movies_step3.csv'

# Enregistrer le DataFrame en fichier CSV
df_exploded.to_csv(file_path)

print(f"Le fichier CSV a Ã©tÃ© enregistrÃ© Ã  : {file_path}")

Le fichier CSV a Ã©tÃ© enregistrÃ© Ã  : C:/Users/Lulu/Documents/Git/Projet_2/movies_step3.csv

In [17]:
liste_profession = df_exploded['primaryProfession'].str.split(',').explode().unique().tolist()

KeyboardInterrupt:

In [ ]:
liste_profession

['actor',
 'miscellaneous',
 'producer',
 'actress',
 'soundtrack',
 'archive_footage',
 'music_department',
 'writer',
 'director',
 'stunts',
 'make_up_department',
 'composer',
 'assistant_director',
 'camera_department',
 'music_artist',
 'art_department',
 'editor',
 'cinematographer',
 'casting_director',
 'executive',
 'costume_designer',
 'script_department',
 'art_director',
 'editorial_department',
 'costume_department',
 'animation_department',
 'talent_agent',
 'archive_sound',
 'production_designer',
 'special_effects',
 'production_manager',
 'sound_department',
 'casting_department',
 'visual_effects',
 'location_management',
 'set_decorator',
 'transportation_department',
 '\\N',
 'choreographer',
 'manager',
 'publicist',
 'podcaster',
 'legal',
 'assistant',
 'production_department',
 'electrical_department',
 'accountant']